(function(g){var window=this;'use strict';var B2=function(a){a.publish("cardstatechange",a.bl()&&a.Ep()?1:0)},C2=function(a,b){var c=g.Ta(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},icb=function(a){var b=g.Cm(a);
a=g.Fm(a);return new g.lm(b.x,b.y,a.width,a.height)},jcb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.Vs(a,b,function(){g.Ws(e);c.apply(a,arguments)},d)},F2=function(a){a=g.Xa(a);
delete D2[a];g.Gc(D2)&&E2&&E2.stop()},lcb=function(){E2||(E2=new g.jp(function(){kcb()},20));
var a=E2;a.isActive()||a.start()},kcb=function(){var a=g.$a();
g.wc(D2,function(b){mcb(b,a)});
g.Gc(D2)||lcb()},G2=function(a,b,c,d){g.wp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},mcb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;ncb(a,a.progress);a.progress==1?(a.j=0,F2(a),a.onFinish(),a.ys()):a.isPlaying()&&a.MN()},ncb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},ocb=function(a,b){g.lb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},H2=function(a,b,c,d,e){G2.call(this,b,c,d,e);
this.element=a},pcb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
H2.call(this,a,b,c,d,e)},qcb=function(a){return Math.pow(a,3)},rcb=function(a){return 3*a*a-2*a*a*a},scb=function(a){g.P.call(this);
this.B=a||window;this.j=[]},I2=function(a){return a.baseUrl||null},J2=function(a,b){return g.pn(g.Fl(a,b),function(c){return!!c})},tcb=function(a,b,c){function d(la){var aa=la.hovercardButton;
if(!aa)return null;aa=aa.subscribeButtonRenderer;if(!aa)return null;var pa=f(aa.unsubscribedButtonText),O=f(aa.subscribedButtonText);if(aa.subscribed){var ua=f(aa.subscriberCountWithUnsubscribeText);var y=f(aa.subscriberCountText)}else ua=f(aa.subscriberCountText),y=f(aa.subscriberCountWithSubscribeText);var V=null;if(la.signinEndpoint){V=C2(la,"signinEndpoint","webNavigationEndpointData","url");if(!V){var vb,Sa;V=(Sa=g.S((vb=aa.signInEndpoint)==null?void 0:vb.commandMetadata,g.w1))==null?void 0:
Sa.url}if(!V)return null}return pa&&(O||V)?{subscribed:aa.subscribed,subscribeText:pa,subscribeCount:ua,unsubscribeText:O,unsubscribeCount:y,enabled:aa.enabled,signinUrl:V,classic:la.useClassicSubscribeButton}:null}
function e(la){if(la){var aa=[],pa=la.videoId;pa&&aa.push("v="+pa);(pa=la.playlistId)&&aa.push("list="+pa);(la=la.startTimeSeconds)&&aa.push("t="+la);return"/watch?"+aa.join("&")}}
function f(la){if(!la)return null;var aa=la.simpleText;return aa?aa:la.runs?g.Fl(la.runs,function(pa){return pa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,x=!1,B=null,E=null,F=null,H=null,N=null,M=null;if(h==="VIDEO")g.S(l,g.ty)?m=g.S(l,g.ty).url:(M=g.S(l,g.zQ),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.S(l,g.ty)?m=g.S(l,g.ty).url:(M=g.S(l,g.zQ),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(x=C2(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else h==="WEBSITE"?((F=C2(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=C2(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=C2(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:
null,W="";if(b.metadata){var ia=f(b.metadata);ia&&(W=ia)}return{id:"element-"+c,type:h,title:f(b.title),metadata:W,callToAction:f(b.callToAction),IX:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,FF:p,playlistLength:t,channelId:u,subscribeButton:B,subscribersText:E,isSubscribe:x,targetUrl:m||null,b$:n,sessionData:R?{itct:R}:null,Bea:q,XD:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:J2(b.impressionUrls||[],I2),R9:J2(b.hovercardShowUrls||[],I2),clickUrls:J2(l.loggingUrls||[],I2),visualElement:g.cx(b.trackingParams),productPrice:H,additionalFeesText:N,watchEndpoint:M||null}},ucb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:J2(a.impressionUrls||[],I2),elements:J2(a.elements||[],function(d,e){return tcb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.cx(a.trackingParams));return c},vcb=function(a){g.dU.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.aP(a)||g.cP(a);this.events=new g.WE(this);g.Q(this,this.events);this.events.T(this.player,g.AD("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.BD("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.kc);this.events.T(window,"focus",this.Eca);this.load();var b=g.ne("STYLE");(g.ee("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.se(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},wcb=function(a){return a.player.getVideoData().Ff?"current":a.Z?"new":"current"},K2=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},xcb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=ucb(f,wcb(a))));L2(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.mw;d&&(c.postParams={ad_tracking:d});if(b=g.BLa(b))if(b=g.vd(b),b=g.rd(b))a.C=g.Yr(b,c)},L2=function(a,b,c){c=c===void 0?!0:c;
a.player.qf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&ycb(a);c=[];d=new g.yD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.U({I:"div",S:"ytp-ce-shadow"}),g.lS(a.player,a.B.element,4),a.D=new g.My(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=zcb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.lS(a.player,f.element,4);var h=new g.yD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Acb(a,f,e)}else g.px(new g.vt("buildEndscreenElement null",
e))}a.player.kf(c);a.kc()}},ycb=function(a){var b=g.ex(),c=g.fx();
c&&b&&a.endscreen.visualElement&&g.xr(g.Cx)(void 0,c,b,a.endscreen.visualElement)},zcb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.XD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:M2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:N2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Ap(b.title||"")},va:b.title},{I:"div",S:b.FF?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.XD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:M2(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:N2(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Ap(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.XD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],W:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Ap(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M2(b)}]};c=new g.U(c);var d=g.fe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.rp(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.VU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.XD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.Ap(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],W:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M2(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Bcb(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.XD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.Ap(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M2(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.rp(c.element,"ytp-ce-placeholder");return c},M2=function(a){if(a.IX)var b=a.IX.thumbnails;
return Bcb(b?b[b.length-1].url:null)},Bcb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Acb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.rp(b.element,"ytp-ce-force-expand"),O2(a,c.id,!0)):(g.tp(b.element,"ytp-ce-force-expand"),g.tp(b.element,"ytp-ce-element-hover"),O2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Ccb(a,b,c)});
b.listen("mouseleave",function(){Dcb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.rp(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Ecb(a,c,m)});
b.listen("keypress",function(m){Ecb(a,c,m)});
b.listen("focus",function(){Ccb(a,b,c)});
b.listen("blur",function(){Dcb(a,b,c)});
b.listen("touchstart",function(){Ccb(a,b,c)});
var l=g.he("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.tp(b.element,"ytp-ce-element-hover");g.tp(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=m.keyCode===9&&!m.shiftKey});
d(g.he("ytp-sb-subscribe",b.element));d(g.he("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Ecb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.qp(d,"ytp-ce-element");){g.qp(d,"subscribe-label")&&Fcb(a,b);
if(g.qp(d,"ytp-ce-channel-subscribe"))return;d=g.te(d)}if(!d||g.qp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Dcb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.Bea==="new")Fcb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.vd(N2(a,b.targetUrl)),c=g.rd(c),g.wz(c,void 0,b.sessionData);else{var e=g.oP(a.player.U())||a.player.getVideoData().Ff,f=function(){var h=N2(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.Dr(h);e&&n&&
(n.v||n.list)?a.player.pp(n.v,l,n.list,!1,void 0,m||void 0):g.vz(h,l)};
Fcb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},N2=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.wP(a)+b}else return"";return b},Ccb=function(a,b,c){g.qp(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.rp(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.jp(function(){g.rp(b.element,"ytp-ce-element-hover")},200)).start():g.rp(b.element,"ytp-ce-element-hover"),P2(a,c.R9),O2(a,c.id,!0))},Dcb=function(a,b,c){g.tp(b.element,"ytp-ce-element-hover");
g.tp(b.element,"ytp-ce-force-expand");O2(a,c.id,!1)},O2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.vp(a.j[e].element,"ytp-ce-element-shadow-show",c)},P2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||K2(a))c&&c();else{b=Gcb(a,b);var e=0,f=!1,h=new g.jp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.tv(b[a],d)}},Fcb=function(a,b,c){P2(a,b.clickUrls,c);
(a=g.fx())&&b.b$&&g.Mx(a,b.visualElement)},Gcb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Hcb(b[d],c));return a},Hcb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Icb=function(a){return typeof a==="string"?a:""},Q2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Jcb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},R2=function(a){return a.value?a.value:null},S2=function(a){if(!a)return null;
var b=g.vd(Icb(a.value));b=g.rd(b);if(!b)return null;var c=Q2(a.target,Kcb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new Jcb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},Lcb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Ocb=function(a){if(!a)return null;
var b=Q2(a.type,Mcb),c=Q2(a.trigger,Ncb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=S2(a?a:null);return b?new Lcb(b,c,a):null},Pcb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Qcb=function(a,b){return g.qb(a.action,b)},Rcb=function(a,b){this.context=a;
this.j=b},Scb=function(a){return a.customMessage?T2("div","iv-card-message",a.customMessage):""},U2=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},Tcb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T2("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},T2=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Ap(c);return{I:a,W:b,va:c}},Ucb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jE+");");c.dir=g.Ap(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,W:c,V:d}},V2=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.mj.click,5)}},Vcb=function(a,b){this.merchant=a;
this.price=b},Wcb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Xcb=function(a,b){return b?b:Wcb(a)?"current":"new"},W2=function(a,b){g.P.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Wa=new Map;this.bb=new Map;this.context.J.addEventListener(g.AD("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.BD("annotations_module"),function(d){(d=c.bb.get(d))&&d.apply(c)})},X2=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.NN(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.qb=!1});
a.context.j.listen(b,"touchmove",function(){a.qb=!0})},Ycb=function(a){var b;
return((b=g.S(a,g.ty))==null?0:b.url)?g.S(a,g.ty).url:(a=g.S(a,g.zQ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},Y2=function(a,b,c){return{iZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
G2:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
HM:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Zcb=function(a,b,c){W2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.zb=this.Na=this.Kb=this.C=this.isInitialized=!1;this.cards=[];this.Ab=this.Z=this.La=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Cf=this.Fa=null;this.K=0;this.Ha=new g.jp(function(){},c.X.Vk?4E3:3E3);
g.Q(this,this.Ha);this.fb=new g.jp(function(){});
g.Q(this,this.fb);this.Ca=new Rcb(c,function(e,f,h,l,m,n){X2(d,e,f,h,l,m,n)});
this.Y=new g.U({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.Q(this,this.Y);this.D=this.Y.element;this.Xa=new g.My(this.Y,330);g.Q(this,this.Xa);this.Jb=g.he("iv-drawer-header-text",this.D);this.B=g.he("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Kb&&Z2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.C)&&$2(d)});
this.Ra=new g.WE(this);g.Q(this,this.Ra);this.J.addEventListener("videodatachange",this.au.bind(this))},$cb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){Z2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){$2(a)});
var c=b.headerText;g.ve(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.cx(b.trackingParams);a.N=g.cx(b.closeTrackingParams);a.Cf=g.cx(b.iconTrackingParams)},adb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.$x(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,mj:{},Hp:null,Sj:e.trackingParams?g.cx(e.trackingParams):null,Cf:f&&f.trackingParams?g.cx(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
jE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};a3(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.$x(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:b3(a,c,b,f),sponsored:!1,mj:Y2(f,e,f.command),Hp:f.trackingParams?g.cx(f.trackingParams):null,Sj:e.trackingParams?g.cx(e.trackingParams):null,Cf:l&&l.trackingParams?g.cx(l.trackingParams):null,imageUrl:c3(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.$x(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,jE:null,title:f.title?g.$x(f.title):"",customMessage:f.callToAction?g.$x(f.callToAction):"",url:g.S(f.command,g.ty).url?S2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.ty).url}):null,onClickCommand:null};a3(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.$x(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:b3(a,c,b,e),sponsored:!1,mj:Y2(e,f,e.endpoint),Hp:e.trackingParams?g.cx(e.trackingParams):null,Sj:f.trackingParams?g.cx(f.trackingParams):null,Cf:l&&l.trackingParams?g.cx(l.trackingParams):null,channelId:g.S(e.endpoint,g.TQ).browseId,customMessage:e.customText?g.$x(e.customText):null,profileImageUrl:c3(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.$x(e.channelName):"",metaInfo:[e.subscriberCountText?g.$x(e.subscriberCountText):""],url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,g.TQ).canonicalBaseUrl?g.S(e.endpoint,g.TQ).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,g.TQ).browseId}),onClickCommand:null};a3(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.$x(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b3(a,c,b,e),sponsored:!1,mj:Y2(e,f,e.action),Hp:e.trackingParams?g.cx(e.trackingParams):null,Sj:f.trackingParams?g.cx(f.trackingParams):null,Cf:l&&l.trackingParams?g.cx(l.trackingParams):null,UH:c3(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.$x(e.customMessage):null,playlistVideoCount:g.$x(e.playlistVideoCount),title:e.playlistTitle?g.$x(e.playlistTitle):"",metaInfo:[e.channelName?g.$x(e.channelName):
"",e.videoCountText?g.$x(e.videoCountText):""],url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Ycb(e.action)}),onClickCommand:null};a3(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.$x(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b3(a,c,b,e),sponsored:!1,mj:Y2(e,f,e.action),Hp:e.trackingParams?g.cx(e.trackingParams):null,Sj:f.trackingParams?g.cx(f.trackingParams):null,Cf:l&&l.trackingParams?g.cx(l.trackingParams):null,UH:c3(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.$x(e.lengthString):null,customMessage:e.customMessage?g.$x(e.customMessage):null,title:e.videoTitle?g.$x(e.videoTitle):"",metaInfo:[e.channelName?g.$x(e.channelName):
"",e.viewCountText?g.$x(e.viewCountText):""],isLiveNow:!!e.badge,url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Ycb(e.action)}),onClickCommand:null};a3(a,b)}}}}}a.K++},c3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},b3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},cdb=function(a,b){if(b=bdb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.wf.id),g.se(b.EO),g.ub(a.cards,b),a.YI(),d3(a)},Z2=function(a,b,c){if(!a.C){a.Xa.show();
a.Va=new g.jp(function(){g.rp(a.context.J.getRootNode(),g.xX.IV_DRAWER_OPEN)},0);
a.Va.start();a.Ra.T(a.B,"mousewheel",function(h){a.Ha.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.fx();d&&a.Fa&&a.N&&g.Kx(d,[a.Fa,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.j_||(f.j_=!0,ddb(a.context.logger,f.wf.mj.iZ,b)),d&&g.Kx(d,[f.wf.Hp]);B2(a.J);c&&(a.G=new g.jp(function(){a.La=a.Z;a.Ab.focus()},330),a.G.start())}},$2=function(a){a.C&&(a.Xa.hide(),g.bt(a.Ra),g.tp(a.context.J.getRootNode(),g.xX.IV_DRAWER_OPEN),a.C=!1,B2(a.J),a.G&&a.G.stop(),a.G=new g.jp(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},edb=function(a){g.sp(a.Ib(),
[g.xX.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.lS(a.J,a.D,5);a.KI();a.Z=g.he("ytp-cards-button",a.J.getRootNode());a.Ab=g.he("iv-drawer-close-button",a.D);a.isInitialized=!0},fdb=function(a){a.qa.push(g.Lv("iv-teaser-shown",a.t6,a));
a.qa.push(g.Lv("iv-teaser-hidden",a.v$,a));a.qa.push(g.Lv("iv-teaser-clicked",a.s6,a));a.zb=!0},gdb=function(a,b){var c;
return b.onClickCommand&&((c=g.S(b.onClickCommand,g.aab))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.ra=b,!0):!1},hdb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.SP(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.S(h[0],g.MRa))==null?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},a3=function(a,b){if(!gdb(a,b)||hdb(a,b)){var c=idb(a,b);
if(c){var d={wf:b,EO:c.element,j_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.zb||fdb(a),cdb(a,b.id),c=a.findLastIndex(d),g.Fb(a.cards,c,0,d));else{a.isInitialized||edb(a);cdb(a,b.id);var e=a.findLastIndex(d);g.Fb(a.cards,e,0,d);c.Ja(a.B,e);a.YI()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,d3(a),jdb(a,d),Z2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&kdb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){kdb(a,d)}),d3(a))}}},idb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=Ucb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?R2(b.url)||"":""},V:[U2(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[T2("h2",void 0,b.title),d]}]}]};c=new g.U(c);V2(a,g.ge("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],W:{href:R2(b.url)||"","data-ytid":b.channelId},V:[U2(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Scb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},Tcb(b)]}]}]};c=new g.U(c);V2(a,g.ge("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:R2(b.url)||""},V:[U2(b.UH,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Scb(b),T2("h2","iv-card-primary-link",b.title),Tcb(b)]}]}]};
c=new g.U(c);V2(a,g.ge("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=b.offers.length!=0;c=["iv-card"];d="";var f=Ucb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?R2(b.url)||"":"";c={I:"div",Ma:c,W:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[T2("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.ne("span");g.ve(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Dd(d,"adInfo");V2(a,g.ge("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:((c=b.url)==null?void 0:R2(c))||""},V:[U2(b.UH,d),{I:"div",S:"iv-card-content",V:[Scb(b),T2("h2","iv-card-primary-link",b.title),Tcb(b),f]}]}]};c=new g.U(e);V2(a,g.ge("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},ldb=function(a){if(a.j)return a.j.wf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.Gl(a.cards,function(c){return c.wf.type==="productListing"})}return g.Gl(a.cards,function(c){return c.wf.type==="productListing"})},d3=function(a){g.vp(a.J.getRootNode(),"ytp-cards-shopping-active",ldb(a))},kdb=function(a,b){if(!g.qp(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.fx(),d=a.j?a.j.wf.Cf:a.Cf;
c&&d&&g.Lx(c,[d]);a.j=b;d3(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.wf.teaserDurationMs&&a.J.jC(!0,{teaserText:b.wf.teaserText,durationMs:b.wf.teaserDurationMs,onClickCommand:b.wf.onClickCommand});a.fb.isActive()||((!a.C||!a.Ha.isActive()&&a.Na)&&jdb(a,b),a.fb.start(910+b.wf.teaserDurationMs))}},jdb=function(a,b){a.Y.Hb?(b=new G2([0,
a.B.scrollTop],[0,b.EO.offsetTop],600,rcb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.Wx(a.Y,!0),a.B.scrollTop=b.EO.offsetTop,g.Wx(a.Y,!1))},e3=function(a){return a.j&&a.j.wf?a.j.wf:a.cards[0]&&a.cards[0].wf?a.cards[0].wf:null},bdb=function(a,b){return g.qb(a.cards,function(c){return c.wf.id===b})},f3=function(a,b,c){W2.call(this,a,b);
this.annotation=c;this.isActive=!1},mdb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},g3=function(a,b,c){f3.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},ndb=function(a,b){var c=c===void 0?0:c;
var d=icb(b).width;g.Am(b,d);c=new pcb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,qcb);g.Q(a,c);a.context.C.listen(c,"begin",function(){g.Gm(b,!0)});
c.play()},qdb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.VU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Gm(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.om(l,"right",b.image_width+"px");g.pe(a.Ib(),l);a.C=new g.jp(function(){odb(a,h,l)},500);
g.Q(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){pdb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},pdb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Fm(b);a.j||(b.style.width=g.zm(f.width,!0),c.style.width=g.zm(f.width,!0));g.om(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.om(d,"right","1px");a.D=!0;g.Gm(b,!0);a.G=new g.jp(function(){g.rp(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},odb=function(a,b,c){g.tp(a.Ib(),"iv-branding-active");
a.K=new g.jp(function(){g.Gm(b,!1);a.j||(c.style.width=g.zm(0,!0))},250);
a.K.start();a.D=!1},rdb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},sdb=function(a,b,c){f3.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.jp(function(){d.j.setAttribute("aria-hidden","true");g.Gm(d.C,!1);g.Gm(d.B,!0)},700,this);
g.Q(this,this.G)},vdb=function(a,b,c){c.stopPropagation();
tdb(a);udb(a,b);a.j.focus()},wdb=function(a){a.isCollapsed||a.Z||a.D||(g.rp(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},tdb=function(a){a.G.stop();
a.isCollapsed&&(g.up(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Gm(a.B,!1),g.Gm(a.C,!0))},udb=function(a,b){a.D||(a.D=g.Se(function(){xdb(this);
wdb(this)},b,a))},xdb=function(a){a.D&&(g.Na.clearTimeout(a.D),a.D=null)},ydb=function(a){this.J=a},ddb=function(a,b,c){b&&(c?h3(a,b.map(function(d){return g.Lo(d,c)})):h3(a,b))},h3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.tv(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},zdb=function(a){g.dU.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new ydb(this.player);this.D=new g.WE(this);this.G=this.N=null;this.events=new g.WE(this);this.Xg=this.Y=this.j=null;this.ra=[];g.Q(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.u6,this);this.subscribe("resize",this.yL,this);this.player.U().Na.subscribe("vast_info_card_add",this.B0,this);g.Q(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.U({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.Q(this,this.B);g.lS(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Ma:["ytp-iv-video-content"]});g.Q(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.qv()&&this.load();var c=this.createElement({I:"style"});(g.ee("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.se(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Adb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.Gm(a,!1);return a},Bdb=function(a,b){b=!b.isCued()&&!g.X(b,1024);
g.Wx(a.B,b);g.Wx(a.C,b)},Cdb=function(a,b,c){a.Z=!0;
a.G=g.Yr(b,c)},Ddb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Va(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ddb(a,e))}return c},Hdb=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.Nr(h)&&h.responseXML?h.responseXML:null)&&Edb(a,h)}};
g.Et()&&(d.onFinish=Fdb(a,d.onFinish));d.postParams={ic_only:"1"};Gdb(d,c);a.Z=!0;g.Yr(b.Wa,d)}}},Gdb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.dJ&&(a.postParams.ic_coll=b.dJ);b.FO&&(a.postParams.ic_xml=b.FO);b.MM&&(a.postParams.ic_track=b.MM)},Idb=function(a){var b=new g.U({I:"div"});
g.Gm(b.element,!1);var c=new Zcb(a.player,b.element,i3(a));g.Q(c,b);b.Ja(a.B.element);c.EH();return c},Kdb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.qa=!0,Jdb(a,b),b.headerText&&a.Xg&&(c=g.$x(b.headerText),a.Xg.setAttribute("title",c))},i3=function(a){if(!a.Y){var b=new scb(a);
g.Q(a,b);var c=new g.Ek(a);g.Q(a,c);a.Y=new rdb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Cj)}return a.Y},Edb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.fx();if(e){var f=g.ex();f&&g.xr(g.Bx)(void 0,e,f,[g.cx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Ddb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=Q2(f.type,Ldb),p=Q2(f.style,Mdb),q=Icb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=Ocb;if(t==null)var u=null;else if(g.Ta(t)){l=[];for(var x=g.v(t),B=x.next();!B.done;B=x.next()){var E=f(B.value);
E&&l.push(E)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new Pcb(m,n,p,u,r):null}else e=null}catch(ia){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=Adb(f),N=null;switch(l.type){case "branding":if(f.player.U().Fd)break;f.B.element.appendChild(H);N=new g3(H,i3(f),l);break;case "promotion":g.lS(f.player,H,4),N=new sdb(H,i3(f),l)}N&&N.EH();if(f=N)g.Q(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=Idb(a),g.Q(a,a.j));if(e.type==="card"){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={iZ:f.impression,click:f.click,close:f.close,G2:f.teaser_impression,HM:f.teaser_click},l=e.tracking_params||{},N=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,Hp:l.card?g.cx(l.card):null,Sj:l.teaser?g.cx(l.teaser):null,Cf:l.icon?g.cx(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a3(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,
Hp:l.card?g.cx(l.card):null,Sj:l.teaser?g.cx(l.teaser):null,Cf:l.icon?g.cx(l.icon):null,UH:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a3(H,c);break;case "productListing":e.signin_url&&(N=S2({target:"current",value:e.signin_url}));M=[];for(var R=e.offers||[],W=0;W<R.length;W++)M.push(new Vcb(g.Yd(R[W].merchant),
g.Yd(R[W].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,Hp:l.card?g.cx(l.card):null,Sj:l.teaser?g.cx(l.teaser):null,Cf:l.icon?g.cx(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,jE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Cpa:N,Bpa:e.signin_title?e.signin_title:void 0,Apa:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};a3(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,Hp:l.card?g.cx(l.card):
null,Sj:l.teaser?g.cx(l.teaser):null,Cf:l.icon?g.cx(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,jE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a3(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,mj:f,Hp:l.card?g.cx(l.card):null,Sj:l.teaser?g.cx(l.teaser):null,Cf:l.icon?g.cx(l.icon):null,UH:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:S2({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},a3(H,c)}}else $cb(a.j,e);c=!0}}c&&
(B2(a.player),a.yL())},Jdb=function(a,b){var c=!1;
a.j||(a.j=Idb(a),g.Q(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(adb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.$Q(f)||(c=a.j,d=b.headerText?g.$x(b.headerText):"",g.ve(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.cx(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.cx(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Cf=b.icon.infoCardIconRenderer.trackingParams?g.cx(b.icon.infoCardIconRenderer.trackingParams):null,a.yL());B2(a.player)}},Ndb=function(a,b,c,d,e){if(!a.player.U().Fd){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,g.TQ)&&g.S(b.navigationEndpoint,g.TQ).browseId&&f.push(new Lcb("openUrl","click",new Jcb("/channel/"+g.S(b.navigationEndpoint,g.TQ).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.UQ)){d.channel_id=g.S(b.subscribeButton,g.UQ).channelId;var l;b=g.S(b.subscribeButton,g.UQ);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.$x(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.$x(b.subscriberCountText))):(b.subscriberCountText&&(e=g.$x(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.$x(b.subscriberCountWithSubscribeText)));var m,n=((m=g.S((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.w1))==null?void 0:m.url)||"";l={subscribeText:g.$x(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.$x(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Pcb(c,"branding","branding",f,d);l=Adb(a);a.B.element.appendChild(l);f=new g3(l,i3(a),f);f.EH();g.Q(f,f);a.K[c]=f}},Fdb=function(a,b){return function(){var c=g.Fa.apply(0,arguments);
a.Ka()||a.ra.push(g.cp.Ti(function(){b.apply(null,g.w(c))}))}},Odb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.LR.prototype.jC=g.da(35,function(a,b){var c=g.DU(this.Bb());c&&c.jC(a,b)});
var D2={},E2=null;g.ab(G2,g.wp);g.k=G2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;F2(this);this.startTime=a=g.$a();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.pL();this.On("play");this.isPaused()&&this.On("resume");this.j=1;var b=g.Xa(this);b in D2||(D2[b]=this);lcb();mcb(this,a);return!0};
g.k.stop=function(a){F2(this);this.j=0;a&&(this.progress=1);ncb(this,this.progress);this.onStop();this.ys()};
g.k.pause=function(){this.isPlaying()&&(F2(this),this.j=-1,this.On("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.On("destroy");G2.Of.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.MN=function(){this.On("animate")};
g.k.On=function(a){this.dispatchEvent(new ocb(a,this))};
g.ab(ocb,g.lb);g.ab(H2,G2);H2.prototype.C=function(){};
H2.prototype.MN=function(){this.C();H2.Of.MN.call(this)};
H2.prototype.ys=function(){this.C();H2.Of.ys.call(this)};
H2.prototype.pL=function(){this.C();H2.Of.pL.call(this)};
g.ab(pcb,H2);pcb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(scb,g.P);g.k=scb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.Ya)(c,d||this.B);a=g.Vs(a,b,c);this.j.push(a);return a};
g.k.XF=function(a,b,c,d){c=(0,g.Ya)(c,d||this.B);a=jcb(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.Ws(a);g.ub(this.j,a)};
g.k.removeAll=function(){g.Ws(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.P.prototype.xa.call(this)};g.z(vcb,g.dU);g.k=vcb.prototype;g.k.load=function(){g.dU.prototype.load.call(this);if(!K2(this)){var a=g.CLa(this.player.getVideoData());a?(a=ucb(a,wcb(this)),L2(this,a,!1)):xcb(this)}};
g.k.unload=function(){L2(this,null);this.C&&(this.C.abort(),this.C=null);g.dU.prototype.unload.call(this)};
g.k.Th=function(a,b){return K2(this)?a==="loadCustomEndscreenRenderer"?(a=ucb(b,"new"),L2(this,a),!0):null:null};
g.k.getOptions=function(){return K2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.kc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Pdb.length;f++){var h=Math.abs(b.width-Pdb[f]);if(e===-1||d>=h)e=f,d=h}d=Qdb[e];this.B&&g.om(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Em(e.element,m,f);g.Am(e.element,n,p);g.up(e.element,Rdb);m>256||f>256?g.rp(e.element,"ytp-ce-large-round"):m>96||f>96?g.rp(e.element,"ytp-ce-medium-round"):g.rp(e.element,"ytp-ce-small-round");g.up(e.element,Sdb);m=h.left+h.width/2;h=h.top+l/2;g.rp(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.up(e.element,Qdb);g.rp(e.element,d);(e=g.fe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.om(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")P2(this,this.endscreen.impressionUrls),(a=g.fx())&&this.endscreen.visualElement&&g.Jx(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.rp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.rp(b,"ytp-ce-shown");P2(this,c.impressionUrls);(b=g.fx())&&g.Jx(b,c.visualElement);this.player.U().N&&this.player.gb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.tp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.tp(b,"ytp-ce-shown");this.player.U().N&&this.player.gb("endscreenelementhidden",a)}};
g.k.Eca=function(a){var b=this;a.target===window&&(new g.jp(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.up(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Pdb=[346,426,470,506,570,640,853,1280,1920],Qdb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Sdb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Rdb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Kcb={Xga:"current",Bja:"new"};var Mcb={CLOSE:"close",Gja:"openUrl",SUBSCRIBE:"subscribe"},Ncb={Gga:"click",CLOSE:"close",Xha:"hidden",tka:"rollOut",uka:"rollOver",Eka:"shown"};Pcb.prototype.De=function(){var a=Qcb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var Mdb={Ofa:"anchored",Z3:"branding",CHANNEL:"channel",Wga:"cta",aia:"highlightText",Qia:"label",PLAYLIST:"playlist",POPUP:"popup",Mka:"speech",SUBSCRIBE:"subscribe",Xka:"title",VIDEO:"video",Jla:"website"},Ldb={Z3:"branding",tga:"card",iha:"drawer",Zha:"highlight",gja:"marker",bka:"promotion",TEXT:"text",mma:"widget"};g.z(W2,g.P);g.k=W2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.yD(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.bb.set(a,e);this.context.J.kf([a])};
g.k.EH=function(){this.context.B.subscribe("resize",this.YI,this)};
g.k.Ib=function(){return this.element};
g.k.NN=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.se(this.Ib())};
g.k.YI=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R2(a);if(f){var h=Xcb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Ff||!1,n=g.Dr(f||"");m&&n&&(n.v||n.list)?e.context.J.pp(n.v,b,n.list,!1):g.wz(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);h3(this.context.logger,c,l,d);Wcb(f)||(c=g.fx(),d=b.itct,c&&d&&g.Mx(c,g.cx(d)))}};
g.k.xa=function(){this.Wa.clear();this.bb.clear();g.P.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.Q(this,a);return a.element};g.z(Zcb,W2);g.k=Zcb.prototype;g.k.au=function(){this.ra&&a3(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Fm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.YI=function(){var a=this.isAvailable();g.Gm(this.Ib(),a);g.vp(this.context.J.getRootNode(),g.xX.IV_DRAWER_ENABLED,a);B2(this.J)};
g.k.destroy=function(){this.J.jC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.Mv(this.qa);g.bt(this.Ra);this.Va&&this.Va.dispose();this.G&&this.G.dispose();W2.prototype.destroy.call(this)};
g.k.KI=function(){var a=this,b=g.he("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.u7,this);this.context.j.listen(this.B,"touchend",function(){a.Ha.start()});
this.context.j.listen(this.B,"scroll",this.S7,this);this.context.B.subscribe("onHideControls",function(){a.Na=!0});
this.context.B.subscribe("onShowControls",function(){a.Na=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.qp(a.J.getRootNode(),"ytp-autohide")});
this.qa.push(g.Lv("iv-button-shown",this.u$,this));this.qa.push(g.Lv("iv-button-hidden",this.t$,this));fdb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.rb(this.cards,function(c){return a.wf.startMs>c.wf.startMs||a.wf.startMs===c.wf.startMs&&a.wf.timestamp>=c.wf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.u7=function(){if(this.C){h3(this.context.logger,e3(this).mj.close);var a=g.fx();a&&this.N&&g.Mx(a,this.N);$2(this)}};
g.k.S7=function(){g.vp(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.u$=function(){var a=g.fx(),b=e3(this);b=b?b.Cf:this.Cf;a&&b&&g.Kx(a,[b])};
g.k.t$=function(){var a=g.fx(),b=e3(this);b=b?b.Cf:this.Cf;a&&b&&g.Lx(a,[b])};
g.k.t6=function(){var a=e3(this);h3(this.context.logger,a.mj.G2);var b=g.fx();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Sj&&c.push(a.Sj);a.Cf&&c.push(a.Cf);c.length>0&&g.Kx(b,c)}else g.Kx(b,[a.Sj,a.Cf])};
g.k.v$=function(){var a=g.fx(),b=e3(this);a&&b&&g.Lx(a,[b.Sj])};
g.k.s6=function(a){var b=e3(this),c=g.fx();this.j?a?(a=this.context.logger,h3(a,b.mj.HM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Sj&&g.Mx(c,b.Sj)):(a=this.context.logger,h3(a,b.mj.HM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Cf&&g.Mx(c,b.Cf)):(a=this.context.logger,h3(a,b.mj.HM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Cf&&g.Mx(c,this.Cf))};g.z(f3,W2);f3.prototype.EH=function(){W2.prototype.EH.call(this);mdb(this)};
f3.prototype.show=function(){W2.prototype.show.call(this);var a=g.fx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Kx(a,[g.cx(b.itct)])};
f3.prototype.hide=function(){W2.prototype.hide.call(this);var a=g.fx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Lx(a,[g.cx(b.itct)])};g.z(g3,f3);
g3.prototype.By=function(){g.rp(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Gm(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.De();c&&X2(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||qdb(this,
a)};
g3.prototype.show=function(){if(!this.isActive&&(f3.prototype.show.call(this),this.N||(this.By(),this.N=!0),g.Gm(this.Ib(),!0),this.isActive=!0,this.B)){try{ndb(this,this.B)}catch(a){}g.rp(this.context.J.getRootNode(),"ytp-branding-shown")}};
g3.prototype.hide=function(){this.isActive&&(f3.prototype.hide.call(this),g.Gm(this.Ib(),!1),this.isActive=!1,g.tp(this.context.J.getRootNode(),"ytp-branding-shown"))};
g3.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);f3.prototype.destroy.call(this)};g.z(sdb,f3);g.k=sdb.prototype;
g.k.By=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.De(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&X2(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Od(f,R2(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&X2(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.rp(this.j,"iv-click-target");e&&X2(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.rp(this.j,"iv-click-target"),e&&X2(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){vdb(a,5E3,q)});
c.appendChild(this.B);g.Gm(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.u9,this);this.context.j.listen(this.Ib(),"mouseout",this.t9,this);this.context.j.listen(this.Ib(),"touchend",function(q){vdb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.p9:this.o9,this);c.appendChild(this.C);g.sp(this.Ib(),d);h&&(g.pe(this.Ib(),h),n&&h.appendChild(n));g.pe(this.Ib(),this.N);g.pe(this.Ib(),c)};
g.k.show=function(){this.isActive||(f3.prototype.show.call(this),this.Y||(this.By(),this.Y=!0),g.Gm(this.Ib(),!0),g.Se(function(){g.tp(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,xdb(this),tdb(this),udb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.rp(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.NN=function(a,b,c,d,e,f){return this.isCollapsed?!1:f3.prototype.NN.call(this,a,b,c,d,e,f)};
g.k.u9=function(a){this.Z=!0;vdb(this,500,a)};
g.k.t9=function(){this.Z=!1;wdb(this)};
g.k.o9=function(a){a.stopPropagation();this.hide()};
g.k.p9=function(a){a.stopPropagation();xdb(this);this.isCollapsed=!0;g.rp(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();f3.prototype.destroy.call(this)};g.z(zdb,g.dU);g.k=zdb.prototype;g.k.Th=function(a,b){if(!Odb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.b1(b))&&Edb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(cdb(this.j,b),B2(this.player)),!0}return null};
g.k.getOptions=function(){return Odb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.qv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.nR(b)||g.AR(this.player.app)?!1:c===1&&!b.fZ||a.Na.get(b.videoId)||g.aR(b)||g.bR(b)?!0:!1};
g.k.yL=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Em(this.C.element,a.width,a.height);g.Am(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Yn();a=this.j;b=b.width;g.vp(a.D,"iv-drawer-small",b<=426);g.vp(a.D,"iv-drawer-big",b>=1280)}};
g.k.u6=function(a){Bdb(this,a.state);g.X(a.state,2)&&(this.bl()&&this.Ep()&&this.player.getPresentingPlayerType()!==2&&this.kC(!1),this.jC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Nr(h)&&h.responseXML?h.responseXML:null)&&(Edb(b,h),g.rp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.dU.prototype.load.call(this);Bdb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Et()&&(a=Fdb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Gdb(e,f);f=f&&(f.FO||f.dJ);if(!c.Pv||f)c.Wa?Cdb(this,c.Wa,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.$Q(h))&&!b.qa&&Kdb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.lS(this.player,this.C.element,4);this.yL();(f=g.aR(c))&&Jdb(this,f);(f=g.bR(c))&&f.featuredChannel&&Ndb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Xg=g.he("ytp-cards-button",this.player.getRootNode());g.$Q(c)&&Kdb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&Cdb(this,b.Wa,a)};
g.k.unload=function(){this.player.qf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,B2(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.dU.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.B0=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Hdb(this):this.load())};
g.k.bl=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.qa};
g.k.Ep=function(){return!!this.j&&this.j.C};
g.k.kC=function(a,b,c){b=b===void 0?!1:b;this.bl();this.j&&(a?c?Z2(this.j,c,b):Z2(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):$2(this.j))};
g.k.jC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.B0,this);g.tp(this.player.getRootNode(),g.xX.IV_DRAWER_OPEN);for(var a=this.ra,b=g.cp,c=0,d=a.length;c<d;c++)b.bk(a[c]);this.ra.length=0;g.dU.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.Q(this,a);return a.element};g.cU("annotations_module",zdb);g.cU("creatorendscreen",vcb);})(_yt_player);
