(function(g){var window=this;'use strict';var Hib=function(a,b){a.gb("onAutonavCoundownStarted",b)},i5=function(a,b,c){g.vp(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.fh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.QP&&(b.lengthText?(e=b.lengthText||null,f=b.Fx||null):b.lengthSeconds&&(e=g.hz(b.lengthSeconds),f=g.hz(b.lengthSeconds,!0)));var h=!!d;d=h&&g.OP(d).type==="RD";var l=b instanceof g.QP?b.isLivePlayback:null,m=b instanceof g.QP?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.LD("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.zl(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.zt};b instanceof g.PP&&(c.playlist_length=b.playlistLength);a.update(c)},j5=function(a){var b=a.U(),c=b.D;
g.U.call(this,{I:"a",S:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",
Ma:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},k5=function(a,b){b=b===void 0?!1:b;
g.U.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.U({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.Q(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.U({I:"div",S:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.Q(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Ea("ytp-autonav-endscreen-link-container"),"click",this.MU);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({I:"div",S:"ytp-autonav-overlay"});g.Q(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.U({I:"div",S:"ytp-autonav-endscreen-button-container"});g.Q(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.U({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Cancel autoplay"},va:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.listen("click",this.z4,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.U({I:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play Now"});g.Q(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.listen("click",this.MU,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Iib(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.jp(function(){Jib(c)},
500);
g.Q(this,this.D);this.LU();this.T(a,"autonavvisibility",this.LU);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.y4),this.T(a,"onAutonavCoundownStarted",this.naa))},l5=function(a){var b=a.J.Yn(!0,a.J.isFullscreen());
g.vp(a.container.element,"ytp-autonav-endscreen-small-mode",a.Og(b));g.vp(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.BM);g.vp(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Df());g.vp(a.J.getRootNode(),"countdown-running",a.Dl());g.vp(a.container.element,"ytp-player-content",a.J.Df());g.om(a.overlay.element,{width:b.width+"px"});if(!a.Dl()){a.J.Df()?Kib(a,Math.round(Lib(a)/1E3)):Kib(a);b=!!a.suggestion&&!!a.suggestion.zt;var c=a.J.Df()||!b;
g.vp(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.vp(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.Wx(a.B,a.J.Df());g.vp(a.element,"ytp-enable-w2w-color-transitions",Mib(a))}},Jib=function(a){var b=Lib(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Kib(a,Math.ceil((b-c)/1E3));b-c<=500&&a.Dl()?a.select(!0):a.Dl()&&a.D.start()},Lib=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.zD;return a===-1||a===void 0?8E3:a}return a.J.Qt()>=0?a.J.Qt():g.IC(a.J.U().experiments,"autoplay_time")||1E4},Iib=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.qfa;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Mib=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},Kib=function(a,b){b=b===void 0?-1:b;
a=a.j.Ea("ytp-autonav-endscreen-upnext-header");g.qe(a);if(b>=0){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.oe("Up next in $SECONDS".slice(0,d)));var e=g.ne("span");g.pp(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ve(e,b);a.appendChild(e);a.appendChild(g.oe("Up next in $SECONDS".slice(d+c.length)));return}}g.ve(a,"Up next")},m5=function(a,b){g.U.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},n5=function(a){g.U.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Up Next"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ea("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.jp(this.iJ,5E3,this);this.B=0;var b=this.Ea("ytp-upnext-cancel");this.cancelButton=new g.U({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},va:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.listen("click",this.A4,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.Q(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ea("ytp-upnext-autoplay-icon");this.T(b,"click",this.B4);this.api.createClientVe(b,this,115130);this.NU();this.T(a,"autonavvisibility",this.NU);this.T(a,"mdxnowautoplaying",this.Yaa);this.T(a,"mdxautoplaycanceled",this.Zaa);g.vp(this.element,"ytp-upnext-mobile",this.api.U().B)},Nib=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.zD;return a===-1||a===void 0?8E3:a}return a.api.Qt()>=0?a.api.Qt():g.IC(a.api.U().experiments,"autoplay_time")||1E4},Oib=function(a,b){b=Nib(a,b);
var c=Math,d=c.min;var e=(0,g.T)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.Dl()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Dl()&&a.j.start()},o5=function(a){m5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.N=new g.U({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new k5(this.player);g.Q(this,this.B);this.B.Ja(this.element);a.getVideoData().Tf?this.j=this.B:(this.j=new n5(a),g.lS(this.player,this.j.element,4),g.Q(this,this.j));this.overlay=new g.U({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.Q(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.WE(this);g.Q(this,this.D);g.Q(this,this.table);this.table.Ja(this.element);this.table.show();g.Q(this,this.N);this.N.Ja(this.table.element);this.hide()},p5=function(a){var b=a.Df();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},q5=function(a,b){g.U.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.Y1();this.buttonType===2&&g.rp(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Y1);g.Wx(this,!0)},r5=function(a,b){m5.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Ne=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new q5(a,2);g.Q(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},Pib=function(a){m5.call(this,a,"subscribecard-endscreen");
this.j=new g.U({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",W:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.Q(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.VU("Subscribe",null,"Unsubscribe",null,!0,!1,b.Sl,b.subscribed,"trailer-endscreen",null,a,!1);g.Q(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Ea("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ta);this.Ta();this.hide()},s5=function(a){var b=a.U(),c=g.SE||g.TO?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.U.call(this,{I:"a",Ma:e,W:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",W:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.WE(this);g.Q(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},t5=function(a){m5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.WE(this);g.Q(this,this.B);this.K=new g.jp(function(){g.rp(b.element,"ytp-show-tiles")},0);
g.Q(this,this.K);var c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},V:[g.cy()]});g.Q(this,c);c.Ja(this.element);c.listen("click",this.F4,this);this.table=new g.Tx({I:"div",S:"ytp-endscreen-content"});g.Q(this,this.table);this.table.Ja(this.element);c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},V:[g.dy()]});g.Q(this,c);c.Ja(this.element);c.listen("click",this.E4,this);a.getVideoData().Tf?this.j=new k5(a,!0):this.j=
new n5(a);g.Q(this,this.j);g.lS(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},u5=function(a){return g.pS(a.player)&&a.fE()&&!a.D},v5=function(a){var b=a.Df();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},w5=function(a){m5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new q5(a,1);g.Q(this,this.watchButton);this.watchButton.Ja(this.element);g.H8a(a)&&(this.j=new g.d1(a),g.Q(this,this.j),this.B=new g.U({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},V:[this.j]}),g.Q(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},Tib=function(a){g.dU.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.WE(this);g.Q(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.Js(g.dP(c))&&d&&!g.PR(a)?(this.B=!0,this.endScreen=new r5(a,g.FR(a))):a.fd()?this.endScreen=new w5(a):Qib(a)?(this.D=!0,Rib(this),this.j?this.endScreen=new o5(a):this.endScreen=new t5(a)):c.Ig?this.endScreen=new Pib(a):this.endScreen=new m5(a);g.Q(this,this.endScreen);g.lS(a,this.endScreen.element,4);Sib(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.AD("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.BD("endscreen"),function(e){b.onCueRangeExit(e)})},Rib=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Xl&&a.C===b.Tf)return!1;a.j=b.Xl;a.C=b.Tf;return!0},Qib=function(a){a=a.U();
return a.Ed&&!a.Ig},Sib=function(a){a.player.qf("endscreen");
var b=a.player.getVideoData();b=new g.yD(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.yD(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.kf([b,c])};
g.LR.prototype.Qt=g.da(14,function(){return this.app.Qt()});
g.F_.prototype.Qt=g.da(13,function(){return this.getVideoData().HY});
g.HR.prototype.Ks=g.da(12,function(a){this.Hi().Ks(a)});
g.jV.prototype.Ks=g.da(11,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.qW.prototype.Ks=g.da(10,function(a){this.overflowButton&&this.overflowButton.Ks(a)});
g.HR.prototype.Ls=g.da(9,function(a){this.Hi().Ls(a)});
g.oV.prototype.Ls=g.da(8,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.qW.prototype.Ls=g.da(7,function(a){this.shareButton&&this.shareButton.Ls(a)});
g.HR.prototype.nC=g.da(6,function(a){this.Hi().nC(a)});
g.OU.prototype.nC=g.da(5,function(a){this.vS!==a&&(this.vS=a,this.Uq())});
g.HR.prototype.mC=g.da(4,function(a){this.Hi().mC(a)});
g.qW.prototype.mC=g.da(3,function(a){this.uS!==a&&(this.uS=a,this.Tq())});g.z(j5,g.U);j5.prototype.select=function(){this.J.pp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.JE||void 0)&&this.J.logClick(this.element)};
j5.prototype.onClick=function(a){g.KS(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
j5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.z(k5,g.U);g.k=k5.prototype;g.k.pI=function(a){this.suggestion!==a&&(this.suggestion=a,i5(this.j,a),this.playButton.updateValue("url",this.suggestion.zl()),l5(this))};
g.k.Dl=function(){return this.C>0};
g.k.wC=function(){this.Dl()||(this.C=Date.now(),Jib(this),Hib(this.J,Lib(this)),g.vp(this.J.getRootNode(),"countdown-running",this.Dl()))};
g.k.ly=function(){this.Nq();Jib(this);var a=this.j.Ea("ytp-autonav-endscreen-upnext-header");a&&g.ve(a,"Up next")};
g.k.Nq=function(){this.Dl()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.Nq()};
g.k.MU=function(a){g.KS(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ea("ytp-autonav-endscreen-link-container")&&(a=this.j.Ea("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.gb("innertubeCommand",this.G),this.Nq()):this.select())};
g.k.z4=function(){this.J.logClick(this.cancelButton.element);g.NR(this.J,!0);this.cancelCommand&&this.J.gb("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Iib(this,b);var c;this.cancelCommand=(c=b.pfa)==null?void 0:c.command};
g.k.naa=function(a){if(Mib(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.sz(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.sz(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.sz(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.sz(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.sz(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.sz(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.vp(this.element,"ytp-w2w-animate",!0)}};
g.k.y4=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.vp(this.element,"ytp-w2w-animate",!1)};
g.k.LU=function(){var a=this.J.Df();this.K&&this.Hb!==a&&g.Wx(this,a);l5(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ea("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Og=function(a){return a.width<400||a.height<459};g.z(m5,g.U);g.k=m5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.fE=function(){return!1};
g.k.Df=function(){return!1};
g.k.HZ=function(){return!1};g.z(n5,g.U);g.k=n5.prototype;g.k.iJ=function(){this.notification&&(this.D.stop(),this.Pc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.pI=function(a){this.suggestion=a;i5(this,a,"hqdefault.jpg")};
g.k.NU=function(){g.Wx(this,this.api.Df());this.api.logVisibility(this.element,this.api.Df());this.api.logVisibility(this.Ea("ytp-upnext-autoplay-icon"),this.api.Df());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Df())};
g.k.jba=function(){window.focus();this.iJ()};
g.k.wC=function(a){var b=this;this.Dl()||(g.Nv("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.T)(),this.j=new g.jp(function(){Oib(b,a)},25),Oib(this,a),Hib(this.api,Nib(this,a)));
g.tp(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Dl=function(){return!!this.j};
g.k.ly=function(){this.Nq();this.B=(0,g.T)();Oib(this);g.rp(this.element,"ytp-upnext-autoplay-paused")};
g.k.Nq=function(){this.Dl()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.iJ(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.fh()}),this.C=this.T(this.notification,"click",this.jba),this.D.start())}this.Nq();this.api.nextVideo(!1,a)};
g.k.B4=function(a){!g.ue(this.cancelButton.element,a.target)&&g.KS(a,this.api)&&(this.api.Df()&&this.api.logClick(this.Ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.A4=function(){this.api.Df()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.NR(this.api,!0)};
g.k.Yaa=function(a){this.api.getPresentingPlayerType();this.show();this.wC(a)};
g.k.Zaa=function(){this.api.getPresentingPlayerType();this.Nq();this.hide()};
g.k.xa=function(){this.Nq();this.iJ();g.U.prototype.xa.call(this)};g.z(o5,m5);g.k=o5.prototype;g.k.create=function(){m5.prototype.create.call(this);this.D.T(this.player,"appresize",this.iD);this.D.T(this.player,"onVideoAreaChange",this.iD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.OU);this.D.T(this.player,"onAutonavCancelled",this.C4);this.onVideoDataChange()};
g.k.show=function(){m5.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.NR(this.player,!1);g.pS(this.player)&&this.fE()&&!this.C?(p5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.wC():this.videoData.autonavState===3&&this.j.ly()):(g.NR(this.player,!0),p5(this));this.iD()};
g.k.hide=function(){m5.prototype.hide.call(this);this.j.ly();p5(this)};
g.k.iD=function(){var a=this.player.Yn(!0,this.player.isFullscreen());p5(this);l5(this.B);g.vp(this.element,"ytp-autonav-cancelled-small-mode",this.Og(a));g.vp(this.element,"ytp-autonav-cancelled-tiny-mode",this.HK(a));g.vp(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.om(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.vp(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.AQ(this.videoData);b&&(this.j.pI(b),this.j!==this.B&&this.B.pI(b))}if(a&&a.length)for(b=0;b<Uib.length;++b){var c=Uib[b];if(a&&a[c]){this.videos[b]=new j5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,i5(d,c));g.Q(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.iD()}};
g.k.OU=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Nq(),this.Hb&&this.iD()):(this.K=!0,this.Df()&&(a===2?this.j.wC():a===3&&this.j.ly()))};
g.k.C4=function(a){a?this.OU(1):(this.C=null,this.K=!1)};
g.k.fE=function(){return this.videoData.autonavState!==1};
g.k.Og=function(a){return(a.width<910||a.height<459)&&!this.HK(a)&&!(a.width<=400||a.height<=360)};
g.k.HK=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Df=function(){return this.Hb&&g.pS(this.player)&&this.fE()&&!this.C};
var Uib=[1,3,2,4];g.z(q5,g.U);g.k=q5.prototype;g.k.Y1=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.LS(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.VO(b)){var c={};g.VO(b)&&g.vR(this.J,"addEmbedsConversionTrackingParams",[c]);if(!this.J.L("embeds_web_enable_referring_feature_deprecation")){a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.kL(c,b)}a=g.Zi(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Hb&&this.Z)};
g.k.show=function(){g.U.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.logVisibility()};
g.k.Mc=function(a){g.U.prototype.Mc.call(this,a);this.logVisibility()};g.z(r5,m5);r5.prototype.show=function(){this.player.getPlayerState()!==3&&(m5.prototype.show.call(this),this.Ne.mC(!0),this.Ne.Ls(!0),this.J.U().ke||this.Ne.Ks(!0),this.J.logVisibility(this.element,!0),this.watchButton.Mc(!0))};
r5.prototype.hide=function(){m5.prototype.hide.call(this);this.Ne.mC(!1);this.Ne.Ls(!1);this.Ne.Ks(!1);this.J.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.z(Pib,m5);Pib.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Sl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.z(s5,g.U);s5.prototype.select=function(){this.api.pp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.JE||void 0)&&this.api.logClick(this.element)};
s5.prototype.onClick=function(a){if(g.VO(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.zl(),c={};g.QR(this.api,c,"emb_rel_end");b=g.Zi(b,c);g.LS(b,this.api,a)}else g.KS(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
s5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
s5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Ff?!1:b.D};g.z(t5,m5);g.k=t5.prototype;g.k.create=function(){m5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.er();this.B.T(this.player,"appresize",this.er);this.B.T(this.player,"onVideoAreaChange",this.er);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.hN);this.B.T(this.player,"onAutonavCancelled",this.D4);a=this.videoData.autonavState;a!==this.Y&&this.hN(a);this.B.T(this.element,"transitionend",this.xca)};
g.k.destroy=function(){g.bt(this.B);g.ib(this.stills);this.stills=[];m5.prototype.destroy.call(this);g.tp(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.fE=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Hb;m5.prototype.show.call(this);g.tp(this.element,"ytp-show-tiles");this.player.U().B?g.lp(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.NR(this.player,!1);u5(this)?(v5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.wC():this.videoData.autonavState===3&&this.j.ly()):(g.NR(this.player,!0),v5(this));a!==this.Hb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Hb;m5.prototype.hide.call(this);this.j.ly();v5(this);a!==this.Hb&&this.player.logVisibility(this.element,!1)};
g.k.xca=function(a){a.target===this.element&&this.er()};
g.k.er=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.AQ(d)];if(e.length){g.rp(this.element,"ytp-endscreen-paginate");var f=this.J.Yn(!0,this.J.isFullscreen());if(a=g.FR(this.J))a=a.Gh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;p>0&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&c*n-p<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;p=b*54;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Em(f,n,p);g.om(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.pI(g.AQ(this.videoData));this.j instanceof
k5&&l5(this.j);g.vp(this.element,"ytp-endscreen-takeover",u5(this));v5(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:m%2===0&&l%2===0&&(m<2&&l<2?m===0&&l===0&&(t=2):t=2),q=g.Id(q+this.C,c),t!==0){r=this.stills[h];r||(r=new s5(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var x=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-u-4,E=Math.floor(n*(l+t)/a)-x-4;g.Am(r.element,x,u);g.Em(r.element,E,B);g.om(r.element,"transitionDelay",
(m+l)/20+"s");g.vp(r.element,"ytp-videowall-still-mini",t===1);g.vp(r.element,"ytp-videowall-still-large",t>2);t=Math.max(E,B);g.vp(r.element,"ytp-videowall-still-round-large",t>=256);g.vp(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.vp(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.qp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",i5(r,q,u),g.VO(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.zl(),u={},g.vR(r.api,"addEmbedsConversionTrackingParams",[u]),r.api.L("embeds_web_enable_referring_feature_deprecation")||g.kL(u,"emb_rel_end"),t=g.Zi(t,u),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.vp(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.se(a.element),g.gb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.AQ(a)?(this.C=0,this.videoData=a,this.er()):this.player.oa("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.E4=function(){this.C+=this.stills.length;this.er()};
g.k.F4=function(){this.C-=this.stills.length;this.er()};
g.k.HZ=function(){return this.j.Dl()};
g.k.hN=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Nq(),this.Hb&&this.er()):(this.G=!0,this.Hb&&u5(this)&&(a===2?this.j.wC():a===3&&this.j.ly()))};
g.k.D4=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.hN(1)}else this.D=null,this.G=!1;this.er()};
g.k.Df=function(){return this.Hb&&u5(this)};g.z(w5,m5);w5.prototype.show=function(){if(this.player.getPlayerState()!==3){m5.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.vp(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.FR(this.player))==null||c.nC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Mc(!0)}};
w5.prototype.hide=function(){m5.prototype.hide.call(this);var a;(a=g.FR(this.player))==null||a.nC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.z(Tib,g.dU);g.k=Tib.prototype;g.k.qv=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.fd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.AQ(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!Qib(this.player)||d;a=a.Ij;c=this.player.WE();return d&&!a&&!c&&!b};
g.k.Df=function(){return this.endScreen.Df()};
g.k.Y9=function(){return this.Df()?this.endScreen.HZ():!1};
g.k.xa=function(){this.player.qf("endscreen");g.dU.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Bb().He.get("heartbeat"),d=g.AQ(a);!d||b.videoId!==d.videoId||a.gW?(this.player.pp(b.videoId,void 0,void 0,!0,!0,b),c&&c.QK("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.dU.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.dU.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.qv()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Sib(this);this.D&&Rib(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new o5(this.player):this.endScreen=new t5(this.player),g.Q(this,this.endScreen),g.lS(this.player,this.endScreen.element,4))};g.cU("endscreen",Tib);})(_yt_player);
